### PR TITLE
Move app title into separate component

### PR DESCRIPTION
**Pull request by drewvolz**
Creates a component for the app title.

Refactoring for possible reuse. Playing around with having the app title on all pages, on some pages, and at least on the search page to start. Makes it easier for reuse.

### CODE REVIEW

**Comment by hawkrives** [comment]
I'd rather not do this independently.

If you get to a point with the shared title where you think that it looks good, I'll take a look, and that can include this change, but until then I'd like it to stay in the current file.

Sorry :|

**Comment by drewvolz** [comment]
> If you get to a point with the shared title where you think that it looks good, I'll take a look [...]

- It is at the point where it is functioning as it did prior to this change.
- It significantly shortened StudentPicker by 28 lines of code.
- It sets anything new up for reusability

... but okay, you’d prefer for it to not be added.

**Comment by hawkrives** [comment]
Yeah, but I have no plans to use it anywhere else, and it actually adds 11 loc overall. 

So, if you want to make a PR that actually uses it elsewhere, I'll be happy to take a look, but I don't want to pull it out just for the sake of pulling it out.

**Comment by drewvolz** [comment]
I’m _about_ to use it, so I don’t see it as “just for the sake of pulling it out”

**Comment by hawkrives** [comment]
Then I will look at it again after you submit another PR.

**Comment by hawkrives** [comment]
And I will look at it as part of said new PR. I don't want it as an independent change.

**Comment by drewvolz** [comment]
> Drew: It significantly shortened StudentPicker by 28 lines of code
> Hawken: it actually adds 11 loc overall. 

My argument is reducing LOC in StudentPicker, which should be as small and componentized as it can be regarding logic to show the StudentPicker. The additional LOC are for what I’m about to do with it. This isn’t increased complexity for the sake of adding code... which I feel you’re trying to make it out to be.

**Pull request closed without merging**
